# Form implementation generated from reading ui file 'windowlistadd3.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogListAdd3(object):
    def setupUi(self, DialogListAdd3):
        DialogListAdd3.setObjectName("DialogListAdd3")
        DialogListAdd3.resize(400, 100)
        DialogListAdd3.setMinimumSize(QtCore.QSize(400, 100))
        DialogListAdd3.setMaximumSize(QtCore.QSize(400, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DialogListAdd3.setWindowIcon(icon)
        self.number_label_3 = QtWidgets.QLabel(DialogListAdd3)
        self.number_label_3.setGeometry(QtCore.QRect(10, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Rubik Medium")
        font.setPointSize(16)
        self.number_label_3.setFont(font)
        self.number_label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.number_label_3.setObjectName("number_label_3")
        self.btn_list_delete3 = QtWidgets.QPushButton(DialogListAdd3)
        self.btn_list_delete3.setGeometry(QtCore.QRect(220, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik Medium")
        font.setPointSize(14)
        self.btn_list_delete3.setFont(font)
        self.btn_list_delete3.setObjectName("btn_list_delete3")
        self.warn_label1_3 = QtWidgets.QLabel(DialogListAdd3)
        self.warn_label1_3.setGeometry(QtCore.QRect(10, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik Medium")
        font.setPointSize(16)
        self.warn_label1_3.setFont(font)
        self.warn_label1_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.warn_label1_3.setObjectName("warn_label1_3")
        self.number_text_3 = QtWidgets.QLineEdit(DialogListAdd3)
        self.number_text_3.setGeometry(QtCore.QRect(170, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Rubik Medium")
        font.setPointSize(16)
        self.number_text_3.setFont(font)
        self.number_text_3.setObjectName("number_text_3")
        self.warn_label2_3 = QtWidgets.QLabel(DialogListAdd3)
        self.warn_label2_3.setGeometry(QtCore.QRect(0, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik Medium")
        font.setPointSize(16)
        self.warn_label2_3.setFont(font)
        self.warn_label2_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.warn_label2_3.setObjectName("warn_label2_3")

        self.retranslateUi(DialogListAdd3)
        QtCore.QMetaObject.connectSlotsByName(DialogListAdd3)

    def retranslateUi(self, DialogListAdd3):
        _translate = QtCore.QCoreApplication.translate
        DialogListAdd3.setWindowTitle(_translate("DialogListAdd3", "Добавление товара в корзину"))
        self.number_label_3.setText(_translate("DialogListAdd3", "Номер товара"))
        self.btn_list_delete3.setText(_translate("DialogListAdd3", "Подтвердить"))
        self.warn_label1_3.setText(_translate("DialogListAdd3", "Введите значение!"))
        self.warn_label2_3.setText(_translate("DialogListAdd3", "Номер отсутствует!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogListAdd3 = QtWidgets.QDialog()
    ui = Ui_DialogListAdd3()
    ui.setupUi(DialogListAdd3)
    DialogListAdd3.show()
    sys.exit(app.exec())
